# Generated by Django 5.0.2 on 2024-02-18 19:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_delete_comment'),
        ('profiles', '0002_userdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdate',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.eventpost'),
        ),
        migrations.AlterField(
            model_name='userdate',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Budget in euros (€)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
